In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_excel('dataset_sales.xlsx')

In [3]:
data.head()

,Order_ID,Order_Date,Product_ID,Product_Name,Category,Price,Quantity,Channel,City,Customer_ID,Stock_Available,Sales,Stock_Status
0,1,2024-05-10,1077,Shoes,Electronics,3610.49,2,Online,Delhi,6959,422,7220.98,Overstock
1,2,2024-12-31,1035,Shoes,Electronics,2164.15,2,Store,Delhi,5426,65,4328.30,Optimal
2,3,2024-11-10,1094,Sofa,Electronics,107.99,1,Store,Bangalore,5728,268,107.99,Optimal
3,4,2022-05-02,1027,Headphones,Electronics,1909.50,3,Store,Delhi,5880,178,5728.50,Optimal
4,5,2023-04-12,1097,Watch,Sports,432.02,4,Store,Bangalore,5561,212,1728.08,Optimal

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         20000 non-null  int64
 1   Order_Date       20000 non-null  datetime64[ns]
 2   Product_ID       20000 non-null  int64
 3   Product_Name     20000 non-null  object
 4   Category         20000 non-null  object
 5   Price            20000 non-null  float64
 6   Quantity         20000 non-null  int64
 7   Channel          20000 non-null  object
 8   City             20000 non-null  object
 9   Customer_ID      20000 non-null  int64
 10  Stock_Available  20000 non-null  int64
 11  Sales            20000 non-null  float64
 12  Stock_Status     20000 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(5), object(5)
memory usage: 2.0+ MB

In [5]:
data.dtypes

Order_ID                    int64
Order_Date         datetime64[ns]
Product_ID                  int64
Product_Name               object
Category                   object
Price                     float64
Quantity                    int64
Channel                    object
City                       object
Customer_ID                 int64
Stock_Available             int64
Sales                     float64
Stock_Status               object
dtype: object

In [6]:
data.describe()

,Order_ID,Order_Date,Product_ID,Price,Quantity,Customer_ID,Stock_Available,Sales
count,20000.000000,20000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,2023-07-09 01:20:51.360000,1049.465650,2554.060570,2.484500,5995.859250,249.780450,6346.054379
min,1.000000,2022-01-01 00:00:00,1000.000000,100.040000,1.000000,5000.000000,0.000000,100.040000
25%,5000.750000,2022-10-05 00:00:00,1025.000000,1348.317500,1.000000,5489.000000,124.000000,2531.942500
50%,10000.500000,2023-07-14 00:00:00,1050.000000,2555.590000,2.000000,5993.000000,249.000000,4902.390000
75%,15000.250000,2024-04-10 00:00:00,1074.250000,3785.065000,3.000000,6504.000000,376.000000,9294.412500
max,20000.000000,2024-12-31 00:00:00,1099.000000,4999.700000,4.000000,6999.000000,499.000000,19998.800000
std,5773.647028,NaN,28.817338,1408.157985,1.115895,581.205845,145.016374,4769.673008

In [7]:
data.describe(include=object)

       Product_Name  Category Channel       City Stock_Status
count         20000     20000   20000      20000        20000
unique            8         4       3          4            3
top           Shirt  Clothing     App  Hyderabad      Optimal
freq           2566      5036    6714       5044         9984

In [8]:
data.isnull().sum()

Order_ID           0
Order_Date         0
Product_ID         0
Product_Name       0
Category           0
Price              0
Quantity           0
Channel            0
City               0
Customer_ID        0
Stock_Available    0
Sales              0
Stock_Status       0
dtype: int64

In [9]:
data.duplicated().sum()

0

In the dataset, some products were mapped to incorrect categories, such as Shoes under Electronics. To fix this data inconsistency, I corrected category values based on product names using mapping techniques and mode-based standardization to ensure accurate dashboard analysis and reporting.

In [10]:
correct_category = {
    'Shoes': 'Fashion',
    'T-Shirt': 'Fashion',
    'Jeans': 'Fashion',
    'Laptop': 'Electronics',
    'Mobile': 'Electronics',
    'Headphones': 'Electronics',
    'Refrigerator': 'Home Appliances',
    'Washing Machine': 'Home Appliances',
    'Sofa': 'Furniture',
    'Table': 'Furniture',
    'Watch': 'Electronics'
}

In [11]:
data['Category'] = data['Product_Name'].map(correct_category)

In [12]:
data.head()

,Order_ID,Order_Date,Product_ID,Product_Name,Category,Price,Quantity,Channel,City,Customer_ID,Stock_Available,Sales,Stock_Status
0,1,2024-05-10,1077,Shoes,Fashion,3610.49,2,Online,Delhi,6959,422,7220.98,Overstock
1,2,2024-12-31,1035,Shoes,Fashion,2164.15,2,Store,Delhi,5426,65,4328.30,Optimal
2,3,2024-11-10,1094,Sofa,Furniture,107.99,1,Store,Bangalore,5728,268,107.99,Optimal
3,4,2022-05-02,1027,Headphones,Electronics,1909.50,3,Store,Delhi,5880,178,5728.50,Optimal
4,5,2023-04-12,1097,Watch,Electronics,432.02,4,Store,Bangalore,5561,212,1728.08,Optimal

In [19]:
category_sales = data.groupby('Category')['Sales'].sum()
category_sales

Category
Electronics    47830062.10
Fashion        15746207.45
Furniture      15319557.84
Name: Sales, dtype: float64

In [21]:
city_sales = data.groupby('City')['Sales'].sum()
city_sales

City
Bangalore    31615445.16
Delhi        31008111.89
Hyderabad    31986934.76
Mumbai       32310595.77
Name: Sales, dtype: float64

In [26]:
monthly_sales = data.groupby(data['Order_Date'].dt.month)['Sales'].sum()

In [27]:
monthly_sales

Order_Date
1     10698417.48
2      9360633.37
3     10781203.15
4     10991391.22
5     10951593.05
6     10110756.39
7     10772708.19
8     10994309.20
9     10753345.97
10    10195335.69
11    10695142.04
12    10616251.83
Name: Sales, dtype: float64

In [29]:
top_products = data.groupby('Product_Name')['Quantity'].sum()
top_products

Product_Name
Bag           6224
Headphones    6281
Laptop        6144
Phone         6252
Shirt         6411
Shoes         6275
Sofa          5975
Watch         6128
Name: Quantity, dtype: int64

In [32]:
Channel_sales = data.groupby('Channel')['Sales'].sum()
Channel_sales

Channel
App       42613335.69
Online    42662759.39
Store     41644992.50
Name: Sales, dtype: float64

In [30]:
data['Customer_ID'].value_counts()

Customer_ID
5342    21
5087    20
5767    19
6210    19
5781    19
        ..
5872     3
5349     3
6781     2
6922     2
5437     2
Name: count, Length: 2000, dtype: int64

In [33]:
top_10_customers = data['Customer_ID'].value_counts().head(10)
top_10_customers

Customer_ID
5342    21
5087    20
5767    19
6210    19
5781    19
6087    19
5935    19
5016    19
6961    19
5153    19
Name: count, dtype: int64

In [34]:
data.to_csv("Cleanded_data.csv",index=False)

In [35]:
data.to_excel("Cleaned_data.xlsx",index=False)